export const portfolioData: Record<"pt" | "en", any> = {
  pt: {
    objetivo: "Estudante de Análise e Desenvolvimento de Sistemas (27 anos) com experiência prática como Estagiária em Análise de Dados no INSS. Possuo conhecimentos em SQL, Python e Excel Avançado, aplicados na manipulação de bases de dados e suporte a processos analíticos. Com histórico em atendimento ao cliente, busco utilizar minha capacidade de resolução de problemas para contribuir com a eficiência da equipe e expandir minhas competências técnicas na área de dados.",
    graduacao: {
      instituicao: "Estácio de Sá",
      curso: "Análise e Desenvolvimento de Sistemas (EAD)",
      status: "3º Semestre | Previsão: Agosto 2027",
      descricao: "Formação superior focada em desenvolvimento de software, análise de sistemas, banco de dados e metodologias ágeis."
    },
    projects: [
      { title: "Meteora - Performance de Vendas", description: "Dashboard estratégico desenvolvido para monitoramento de KPIs e análise de performance comercial regional.", tags: ["Power BI", "DAX", "Excel", "UI Design"], features: ["KPIs de Faturamento e Ticket Médio", "Análise Regional com Market Share", "Ranking dinâmico de Talentos (Top N)", "Foco em UX e Qualidade de Dados"], link: "https://liveestacio-my.sharepoint.com/:u:/g/personal/202506043397_alunos_estacio_br/IQBbiY36CMxGT6rpQUg5mxALAY8e2uvr31IB1p2RdUqiFpk?e=ExeZLz", image: "/dashboard_meteora_performace.png" },
      { title: "CineData", description: "Aplicação web interativa desenvolvida com Streamlit para análise e visualização de dados cinematográficos.", tags: ["Python", "Streamlit", "Pandas", "Plotly"], features: ["Dashboard interativo com filtros dinâmicos", "Análise de tendências temporais", "Visualizações customizadas com Plotly"], link: "https://lnkd.in/dg4DHpk8", image: "/dashboard-filmes.png" },
      { title: "Dashboard de Combustíveis", description: "Dashboard analítico no Power BI processando mais de 420 mil registros de preços de combustíveis no Brasil.", tags: ["Power BI", "DAX", "Power Query", "SQL"], features: ["Processamento de 420k+ registros", "Análises geográficas por região", "KPIs de variação de preços"], link: "https://app.powerbi.com/links/8Rdq51rL08?ctid=da49a844-e2e3-40af-86a6-c3819d704f49&pbi_source=linkShare", image: "/dashboard-gasolina.png" },
      { title: "Gestão Zoop (RH)", description: "Sistema de gestão de RH e Performance desenvolvido para otimizar processos de recursos humanos.", tags: ["Power BI", "Excel", "Python"], features: ["Monitoramento de Turnover", "Análise de Headcount", "Indicadores de Performance"], link: "https://app.powerbi.com/links/wzg90pEuS3?ctid=da49a844-e2e3-40af-86a6-c3819d704f49&pbi_source=linkShare", image: "/dashboard-zoop.png" },
      { title: "Análise de ROI (INSS)", description: "Projeto focado no cálculo e visualização do Retorno sobre Investimento (ROI) para processos internos.", tags: ["Power BI", "Análise Financeira", "Excel"], features: ["Cálculo automatizado de ROI", "Projeções de economia", "Dashboard de eficiência"], disclaimer: "Dados fictícios para fins de demonstração técnica, garantindo a ética e a segurança da informação.", link: "https://liveestacio-my.sharepoint.com/:u:/g/personal/202506043397_alunos_estacio_br/IQAmxKaiUVdXSIn8rWNojlgrAcUktYzZ9DLN0DZS5Dirr_s?e=cPpEpw", image: "/dashboard-inss.png" },
      { title: "Análise de Salários", description: "Exploração de dados salariais utilizando Python e Streamlit para identificar padrões e médias.", tags: ["Python", "Streamlit", "EDA", "Pandas"], features: ["Análise exploratória (EDA)", "Gráficos de distribuição", "Filtros por nível de experiência"], link: "https://lnkd.in/dpGu4P3c", image: "/dashboard-analise-salarios.png" }
    ],
    certificados: [
      { nome: "Power BI: analisando dados de forma inteligente", horas: "12h", org: "Alura", cat: "dados", tag: "Power BI", link: "https://cursos.alura.com.br/certificate/b05a7068-3b80-4676-96a7-e3224cfcd192" },
      { nome: "Power BI: conceitos do uso de DAX", horas: "8h", org: "Alura", cat: "dados", tag: "DAX", link: "https://cursos.alura.com.br/certificate/f448b706-9d5f-4c86-84b4-eaa6ceb29cd9" },
      { nome: "Power BI: modelagem de dados", horas: "8h", org: "Alura", cat: "dados", tag: "Modelagem", link: "https://cursos.alura.com.br/certificate/84e95d59-5522-4c07-afb0-610b2a8f6a77" },
      { nome: "Análise de dados: uma leitura crítica das informações", horas: "23h", org: "Enap", cat: "dados", tag: "Análise", link: "https://drive.google.com/file/d/1UBKqCfvLHkkp7w_ebaTv7XKo7Qz4SEnb/view?usp=drive_link" },
      { nome: "Desenvolvimento de Painéis em Qlik Sense no INSS", horas: "20h", org: "INSS", cat: "dados", tag: "Qlik", link: "https://drive.google.com/file/d/1S5Ap47NbxZMMVZmDHluukM7kE71H_R5P/view?usp=drive_link" },
      { nome: "Data Storytelling: transformando dados em histórias impactantes", horas: "8h", org: "Alura", cat: "dados", tag: "Storytelling", link: "https://cursos.alura.com.br/certificate/ae39e9ee-666f-4fe5-a60e-e74e3fbb532d" },
      { nome: "Introdução à Análise de Dados - Microsoft Power BI", horas: "5h", org: "Enap", cat: "dados", tag: "Power BI", link: "https://drive.google.com/file/d/1htc51HCRYzYhnPwUUMEyPdzX0MI8Za8p/view?usp=drive_link" },
      { nome: "Trabalhando com dados: fundamentos da análise de dados", horas: "6h", org: "Alura", cat: "dados", tag: "Fundamentos", link: "https://cursos.alura.com.br/certificate/7725e671-785a-425f-ae3c-5cc0c6bd28e6" },
      { nome: "Data Science: explorando e analisando dados", horas: "10h", org: "Alura", cat: "dados", tag: "Data Science", link: "https://cursos.alura.com.br/certificate/ad43b2cd-e615-4b57-890a-74b482b16321" },
      { nome: "Python para Dados: primeiros passos", horas: "10h", org: "Alura", cat: "programacao", tag: "Python", link: "https://cursos.alura.com.br/certificate/35c29623-8663-4a41-afbf-55cf536a8d86" },
      { nome: "Python para Dados: trabalhando com funções e estruturas", horas: "8h", org: "Alura", cat: "programacao", tag: "Python", link: "https://cursos.alura.com.br/certificate/99c96695-7ef5-4922-ba53-30989a27203b?lang" },
      { nome: "Pandas: conhecendo a biblioteca", horas: "8h", org: "Alura", cat: "programacao", tag: "Pandas", link: "https://cursos.alura.com.br/certificate/447d30bb-0dd0-4164-a50e-425a10b36eda?lang" },
      { nome: "Pandas I/O: trabalhando com diferentes formatos de arquivos", horas: "8h", org: "Alura", cat: "programacao", tag: "Pandas", link: "https://drive.google.com/drive/folders/16luk6Y9YHMy5Nq4X4npp22wbd7DArKrb" },
      { nome: "MySQL: executando Procedures", horas: "12h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/e9599233-e5c3-4d77-a506-5cbc5ad7d815" },
      { nome: "MySQL: trabalhando com funções", horas: "10h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/471fd18d-5bcd-4051-865a-178f9ea7feef" },
      { nome: "MySQL: conhecendo a ferramenta", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/b4f3f958-1163-41eb-821f-2acddfd02de5" },
      { nome: "MySQL: aplicado para análise de dados", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/1VYRoGjBUAGbRO7PwOKy5Jak3CooPv6YL/view?usp=drive_link" },
      { nome: "Realizando consultas com SQL: Joins, Views e transações", horas: "10h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/f04c0a03-add-4bf4-8082-86a1ef00b1ac" },
      { nome: "SQLite Online: executando consultas SQL", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/14AbPRn5hql8PyrwlAkUhuxg4C4LKZEMN/view?usp=drive_link" },
      { nome: "SQLite Online: conhecendo instruções SQL", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/16n6UMWtxrsywxamyWRTPH1qJefvZQYu_/view?usp=drive_link" },
      { nome: "SQLite Online: análise de dados com SQL", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/20b0c3da-3123-40be-9fb4-06ef3e4a08dc" },
      { nome: "Imersão Dados com Python", horas: "4h", org: "Alura", cat: "programacao", tag: "Python", link: "https://drive.google.com/file/d/1g2p_qN0Z8BR5Ga-7X_hnD04J93xRXT4J/view?usp=drive_link" },
      { nome: "Excel Avançado", horas: "30h", org: "Enap", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/18jOPTEk1z9cjFQAYYcO6oa_UsXgFuSpk/view?usp=drive_link" },
      { nome: "Excel Intermediário", horas: "30h", org: "Enap", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/1tSiO_7V28LGZkWfa9SieDseMrUSN7cFU/view?usp=drive_link" },
      { nome: "Excel para análise de dados: funções, tabelas e gráficos", horas: "10h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://cursos.alura.com.br/certificate/d7f0e63c-3a7b-4131-bf4a-57a0228f1eb6" },
      { nome: "Excel: domine o editor de planilhas", horas: "8h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://cursos.alura.com.br/certificate/18e7626b-c061-44ba-8cf7-283207e72a78" },
      { nome: "Excel: manipulação avançada de dados e automação com IA", horas: "8h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/1ZTwGJU59mqbVY5CRegYVfPD6p6wWkwQb/view?usp=drive_link" },
      { nome: "Atuação do Encarregado na LGPD: A Função de Orientar", horas: "15h", org: "Enap", cat: "gestao", tag: "LGPD", link: "https://drive.google.com/file/d/1-WnfdcQLpYTW2hg-KWg-ZPaM5QvEgb8N/view?usp=drive_link" },
      { nome: "Redação Oficial e Noções de SEI", horas: "10h", org: "Enap", cat: "gestao", tag: "Oficial", link: "https://drive.google.com/file/d/1JTxCvalzbzTPtn8hE0SRKuJzhO_ilZTh/view?usp=drive_link" },
      { nome: "Prevenção e Enfrentamento ao Assédio", horas: "12h", org: "INSS", cat: "gestao", tag: "Ética", link: "https://drive.google.com/file/d/1Nu-ZWX3_ws6G0chCDVU_I4_BQwyLDG5r/view?usp=drive_link" },
      { nome: "Workshop - Microsoft Office 365", horas: "9h", org: "INSS", cat: "gestao", tag: "Office" }
    ],
    notebooks: [
      { title: "Análise de Dados de Aluguéis de Apartamentos", description: "Exploração e processamento de dados desenvolvido diretamente no Google Colab.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\n\n# Carregando dados no Colab\ndf = pd.read_csv('dados.csv')\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1PoL1IvxnaaXh9_-e6BumF7hKxoxAgQ5W" },
      { title: "Análise de Salários na Área de Dados", description: "Explorando tendências e distribuições de salários de profissionais de dados.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "NumPy", "Seaborn", "Matplotlib", "Plotly", "Pycountry"], codeSnippet: "import pandas as pd\nimport matplotlib.pyplot as plt\n\n# Analisando a distribuição de salários\ndf['salary_in_usd'].hist(bins=20)\nplt.title('Distribuição Salarial')", link: "https://colab.research.google.com/drive/1-GruWUyJWeMwDrE92mhForuuEyv7G05S#scrollTo=b6ab5e61" },
      { title: "Explorando Conceitos Fundamentais de Python", description: "Uma Jornada Através de Estruturas de Dados, Funções e Tratamento de Erros.", tags: ["🐍 Python", "📙 Colab", "Matplotlib", "Random", "NumPy", "Math"], codeSnippet: "def calcular_media(valores):\n    try:\n        return sum(valores) / len(valores)\n    except ZeroDivisionError:\n        return 0\n\nprint(calcular_media([10, 20, 30]))", link: "https://colab.research.google.com/drive/16mhApft04H7wCV1W0DxTnQu0ehj75HTv#scrollTo=057774d46" },
      { title: "Análise e Normalização de Dados JSON com Pandas", description: "Carregamento, achatamento (flattening) e análise de estruturas aninhadas de dados JSON.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\nimport json\n\n# Normalizando dados JSON\ndf = pd.json_normalize(dados_json, record_path=['itens'])\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1xh6M_lpgWIck_Yn5Le1Dj_yAovJomsli#scrollTo=a4e26250" },
      { title: "Análise de Dados HTML e XML com Pandas", description: "Explorando Filmes da Wikipedia extraindo dados de tabelas diretamente das páginas.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\n\n# Lendo tabelas HTML da Wikipedia\ntabelas = pd.read_html('url_wikipedia')\ndf_filmes = tabelas[0]\ndisplay(df_filmes.head())", link: "https://colab.research.google.com/drive/19GhehwPymQcEdDxmnKBF1y0t8OwhIz21#scrollTo=c37b8e5f" },
      { title: "Análise de Dados de Clientes com SQL e Pandas", description: "Explorando e manipulando dados com SQL no ambiente Pandas através do SQLAlchemy.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "SQLAlchemy"], codeSnippet: "import pandas as pd\nfrom sqlalchemy import create_engine\n\n# Consultando com SQL via SQLAlchemy\nengine = create_engine('sqlite:///banco.db')\ndf = pd.read_sql('SELECT * FROM clientes', engine)\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1F8S8Z5eALFSfD-WdwyATY7KnfZfSA_W1#scrollTo=b0390d15" },
      { title: "Análise de Churn de Clientes de Telecomunicações", description: "Este notebook explora um dataset de churn de clientes para identificar padrões e fatores que levam à evasão de clientes em uma empresa de telecomunicações. - Curso \"Pandas: limpeza e tratamento de dados\" da Alura", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "JSON", "NumPy", "Seaborn", "Matplotlib"], codeSnippet: "import pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Analisando a distribuição de churn\nsns.countplot(x='Churn', data=df)\nplt.title('Distribuição de Clientes por Churn')\nplt.show()", link: "https://colab.research.google.com/drive/1C8uHGBudiDLvb4eZI-EdvzJnloxgp1ej?usp=sharing" }
    ]
  },
  en: {
    objetivo: "Systems Analysis and Development Student (27 years old) with practical experience as a Data Analysis Intern at INSS. I have knowledge in SQL, Python, and Advanced Excel, applied to database manipulation and analytical processes support. With a background in customer service, I aim to use my problem-solving skills to contribute to team efficiency and expand my technical skills in the data field.",
    graduacao: {
      instituicao: "Estácio de Sá",
      curso: "Systems Analysis and Development (Distance Learning)",
      status: "3rd Semester | Expected: August 2027",
      descricao: "Higher education focused on software development, systems analysis, databases, and agile methodologies."
    },
    projects: [
      { title: "Meteora - Sales Performance", description: "Strategic dashboard developed for KPI monitoring and regional commercial performance analysis.", tags: ["Power BI", "DAX", "Excel", "UI Design"], features: ["Revenue KPIs & Average Ticket", "Regional Analysis with Market Share", "Dynamic Talent Ranking (Top N)", "UX Focus & Data Quality"], link: "https://liveestacio-my.sharepoint.com/:u:/g/personal/202506043397_alunos_estacio_br/IQBbiY36CMxGT6rpQUg5mxALAY8e2uvr31IB1p2RdUqiFpk?e=ExeZLz", image: "/dashboard_meteora_performace.png" },
      { title: "CineData", description: "Interactive web application developed with Streamlit for cinematic data analysis and visualization.", tags: ["Python", "Streamlit", "Pandas", "Plotly"], features: ["Interactive dashboard with dynamic filters", "Temporal trends analysis", "Custom visualizations with Plotly"], link: "https://lnkd.in/dg4DHpk8", image: "/dashboard-filmes.png" },
      { title: "Fuel Dashboard", description: "Analytical dashboard in Power BI processing over 420k fuel price records in Brazil.", tags: ["Power BI", "DAX", "Power Query", "SQL"], features: ["Processed 420k+ records", "Geographic analysis by region", "Price variation KPIs"], link: "https://app.powerbi.com/links/8Rdq51rL08?ctid=da49a844-e2e3-40af-86a6-c3819d704f49&pbi_source=linkShare", image: "/dashboard-gasolina.png" },
      { title: "Zoop Management (HR)", description: "HR and Performance management system developed to optimize human resources processes.", tags: ["Power BI", "Excel", "Python"], features: ["Turnover monitoring", "Headcount analysis", "Performance indicators"], link: "https://app.powerbi.com/links/wzg90pEuS3?ctid=da49a844-e2e3-40af-86a6-c3819d704f49&pbi_source=linkShare", image: "/dashboard-zoop.png" },
      { title: "ROI Analysis (INSS)", description: "Project focused on calculating and visualizing the Return on Investment (ROI) for internal processes.", tags: ["Power BI", "Financial Analysis", "Excel"], features: ["Automated ROI calculation", "Savings projections", "Efficiency dashboard"], link: "https://liveestacio-my.sharepoint.com/:u:/g/personal/202506043397_alunos_estacio_br/IQAmxKaiUVdXSIn8rWNojlgrAcUktYzZ9DLN0DZS5Dirr_s?e=cPpEpw", image: "/dashboard-inss.png" },
      { title: "Salary Analysis", description: "Salary data exploration using Python and Streamlit to identify patterns and averages.", tags: ["Python", "Streamlit", "EDA", "Pandas"], features: ["Exploratory Data Analysis (EDA)", "Distribution charts", "Filters by experience level"], link: "https://lnkd.in/dpGu4P3c", image: "/dashboard-analise-salarios.png" }
    ],
    certificados: [
      { nome: "Power BI: Intelligent Data Analysis", horas: "12h", org: "Alura", cat: "dados", tag: "Power BI", link: "https://cursos.alura.com.br/certificate/b05a7068-3b80-4676-96a7-e3224cfcd192" },
      { nome: "Power BI: DAX Concepts", horas: "8h", org: "Alura", cat: "dados", tag: "DAX", link: "https://cursos.alura.com.br/certificate/f448b706-9d5f-4c86-84b4-eaa6ceb29cd9" },
      { nome: "Power BI: Data Modeling", horas: "8h", org: "Alura", cat: "dados", tag: "Modeling", link: "https://cursos.alura.com.br/certificate/84e95d59-5522-4c07-afb0-610b2a8f6a77" },
      { nome: "Data Analysis: Critical Information Reading", horas: "23h", org: "Enap", cat: "dados", tag: "Analysis", link: "https://drive.google.com/file/d/1UBKqCfvLHkkp7w_ebaTv7XKo7Qz4SEnb/view?usp=drive_link" },
      { nome: "Qlik Sense Dashboard Development at INSS", horas: "20h", org: "INSS", cat: "dados", tag: "Qlik", link: "https://drive.google.com/file/d/1S5Ap47NbxZMMVZmDHluukM7kE71H_R5P/view?usp=drive_link" },
      { nome: "Data Storytelling: Transforming Data into Impactful Stories", horas: "8h", org: "Alura", cat: "dados", tag: "Storytelling", link: "https://cursos.alura.com.br/certificate/ae39e9ee-666f-4fe5-a60e-e74e3fbb532d" },
      { nome: "Introduction to Data Analysis - Microsoft Power BI", horas: "5h", org: "Enap", cat: "dados", tag: "Power BI", link: "https://drive.google.com/file/d/1htc51HCRYzYhnPwUUMEyPdzX0MI8Za8p/view?usp=drive_link" },
      { nome: "Working with Data: Data Analysis Fundamentals", horas: "6h", org: "Alura", cat: "dados", tag: "Fundamentals", link: "https://cursos.alura.com.br/certificate/7725e671-785a-425f-ae3c-5cc0c6bd28e6" },
      { nome: "Data Science: Exploring and Analyzing Data", horas: "10h", org: "Alura", cat: "dados", tag: "Data Science", link: "https://cursos.alura.com.br/certificate/ad43b2cd-e615-4b57-890a-74b482b16321" },
      { nome: "Python for Data: First Steps", horas: "10h", org: "Alura", cat: "programacao", tag: "Python", link: "https://cursos.alura.com.br/certificate/35c29623-8663-4a41-afbf-55cf536a8d86" },
      { nome: "Python for Data: Working with Functions and Structures", horas: "8h", org: "Alura", cat: "programacao", tag: "Python", link: "https://cursos.alura.com.br/certificate/99c96695-7ef5-4922-ba53-30989a27203b?lang" },
      { nome: "Pandas: Getting to Know the Library", horas: "8h", org: "Alura", cat: "programacao", tag: "Pandas", link: "https://cursos.alura.com.br/certificate/447d30bb-0dd0-4164-a50e-425a10b36eda?lang" },
      { nome: "Pandas I/O: Working with Different File Formats", horas: "8h", org: "Alura", cat: "programacao", tag: "Pandas", link: "https://drive.google.com/drive/folders/16luk6Y9YHMy5Nq4X4npp22wbd7DArKrb" },
      { nome: "MySQL: Executing Procedures", horas: "12h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/e9599233-e5c3-4d77-a506-5cbc5ad7d815" },
      { nome: "MySQL: Working with Functions", horas: "10h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/471fd18d-5bcd-4051-865a-178f9ea7feef" },
      { nome: "MySQL: Getting to Know the Tool", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/b4f3f958-1163-41eb-821f-2acddfd02de5" },
      { nome: "MySQL: Applied to Data Analysis", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/1VYRoGjBUAGbRO7PwOKy5Jak3CooPv6YL/view?usp=drive_link" },
      { nome: "Querying with SQL: Joins, Views, and Transactions", horas: "10h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/f04c0a03-add-4bf4-8082-86a1ef00b1ac" },
      { nome: "SQLite Online: Executing SQL Queries", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/14AbPRn5hql8PyrwlAkUhuxg4C4LKZEMN/view?usp=drive_link" },
      { nome: "SQLite Online: Getting to Know SQL Statements", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://drive.google.com/file/d/16n6UMWtxrsywxamyWRTPH1qJefvZQYu_/view?usp=drive_link" },
      { nome: "SQLite Online: Data Analysis with SQL", horas: "8h", org: "Alura", cat: "programacao", tag: "SQL", link: "https://cursos.alura.com.br/certificate/20b0c3da-3123-40be-9fb4-06ef3e4a08dc" },
      { nome: "Data Immersion with Python", horas: "4h", org: "Alura", cat: "programacao", tag: "Python", link: "https://drive.google.com/file/d/1g2p_qN0Z8BR5Ga-7X_hnD04J93xRXT4J/view?usp=drive_link" },
      { nome: "Advanced Excel", horas: "30h", org: "Enap", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/18jOPTEk1z9cjFQAYYcO6oa_UsXgFuSpk/view?usp=drive_link" },
      { nome: "Intermediate Excel", horas: "30h", org: "Enap", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/1tSiO_7V28LGZkWfa9SieDseMrUSN7cFU/view?usp=drive_link" },
      { nome: "Excel for Data Analysis: Functions, Tables, and Charts", horas: "10h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://cursos.alura.com.br/certificate/d7f0e63c-3a7b-4131-bf4a-57a0228f1eb6" },
      { nome: "Excel: Master the Spreadsheet Editor", horas: "8h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://cursos.alura.com.br/certificate/18e7626b-c061-44ba-8cf7-283207e72a78" },
      { nome: "Excel: Advanced Data Manipulation and AI Automation", horas: "8h", org: "Alura", cat: "gestao", tag: "Excel", link: "https://drive.google.com/file/d/1ZTwGJU59mqbVY5CRegYVfPD6p6wWkwQb/view?usp=drive_link" },
      { nome: "LGPD Officer Role: The Function of Guiding", horas: "15h", org: "Enap", cat: "gestao", tag: "LGPD", link: "https://drive.google.com/file/d/1-WnfdcQLpYTW2hg-KWg-ZPaM5QvEgb8N/view?usp=drive_link" },
      { nome: "Official Drafting and SEI Basics", horas: "10h", org: "Enap", cat: "gestao", tag: "Official", link: "https://drive.google.com/file/d/1JTxCvalzbzTPtn8hE0SRKuJzhO_ilZTh/view?usp=drive_link" },
      { nome: "Harassment Prevention and Coping", horas: "12h", org: "INSS", cat: "gestao", tag: "Ethics", link: "https://drive.google.com/file/d/1Nu-ZWX3_ws6G0chCDVU_I4_BQwyLDG5r/view?usp=drive_link" },
      { nome: "Workshop - Microsoft Office 365", horas: "9h", org: "INSS", cat: "gestao", tag: "Office" }
    ],
    notebooks: [
      { title: "Apartment Rentals Data Analysis", description: "Data exploration and processing developed directly in Google Colab.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\n\n# Loading data in Colab\ndf = pd.read_csv('data.csv')\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1PoL1IvxnaaXh9_-e6BumF7hKxoxAgQ5W" },
      { title: "Data Science Salaries Analysis", description: "Exploring trends and distributions of data professionals' salaries.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "NumPy", "Seaborn", "Matplotlib", "Plotly", "Pycountry"], codeSnippet: "import pandas as pd\nimport matplotlib.pyplot as plt\n\n# Analyzing salary distribution\ndf['salary_in_usd'].hist(bins=20)\nplt.title('Salary Distribution')", link: "https://colab.research.google.com/drive/1-GruWUyJWeMwDrE92mhForuuEyv7G05S#scrollTo=b6ab5e61" },
      { title: "Exploring Fundamental Python Concepts", description: "A Journey Through Data Structures, Functions, and Error Handling.", tags: ["🐍 Python", "📙 Colab", "Matplotlib", "Random", "NumPy", "Math"], codeSnippet: "def calculate_average(values):\n    try:\n        return sum(values) / len(values)\n    except ZeroDivisionError:\n        return 0\n\nprint(calculate_average([10, 20, 30]))", link: "https://colab.research.google.com/drive/16mhApft04H7wCV1W0DxTnQu0ehj75HTv#scrollTo=057774d46" },
      { title: "JSON Data Analysis and Normalization with Pandas", description: "Loading, flattening, and analyzing nested JSON data structures.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\nimport json\n\n# Normalizing JSON data\ndf = pd.json_normalize(json_data, record_path=['items'])\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1xh6M_lpgWIck_Yn5Le1Dj_yAovJomsli#scrollTo=a4e26250" },
      { title: "HTML and XML Data Analysis with Pandas", description: "Exploring Wikipedia Movies extracting data directly from page tables.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas"], codeSnippet: "import pandas as pd\n\n# Reading HTML tables from Wikipedia\ntables = pd.read_html('wikipedia_url')\nmovies_df = tables[0]\ndisplay(movies_df.head())", link: "https://colab.research.google.com/drive/19GhehwPymQcEdDxmnKBF1y0t8OwhIz21#scrollTo=c37b8e5f" },
      { title: "Customer Data Analysis with SQL and Pandas", description: "Exploring and manipulating data with SQL in the Pandas environment using SQLAlchemy.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "SQLAlchemy"], codeSnippet: "import pandas as pd\nfrom sqlalchemy import create_engine\n\n# Querying with SQL via SQLAlchemy\nengine = create_engine('sqlite:///database.db')\ndf = pd.read_sql('SELECT * FROM customers', engine)\ndisplay(df.head())", link: "https://colab.research.google.com/drive/1F8S8Z5eALFSfD-WdwyATY7KnfZfSA_W1#scrollTo=b0390d15" },
      { title: "Telecommunications Customer Churn Analysis", description: "This notebook explores a customer churn dataset to identify patterns and factors that lead to customer attrition in a telecommunications company. - Alura's \"Pandas: data cleaning and treatment\" course.", tags: ["🐍 Python", "📙 Colab", "🐼 Pandas", "JSON", "NumPy", "Seaborn", "Matplotlib"], codeSnippet: "import pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n# Analyzing churn distribution\nsns.countplot(x='Churn', data=df)\nplt.title('Customer Distribution by Churn')\nplt.show()", link: "https://colab.research.google.com/drive/1C8uHGBudiDLvb4eZI-EdvzJnloxgp1ej?usp=sharing" }
    ]
  }
};

export const educationData = portfolioData.pt;